#!/bin/bash
python3 endtoend/Galaxy_NLU_postprocess.py Attraction $1
python3 endtoend/Galaxy_NLU_postprocess.py Restaurant $1
python3 endtoend/Galaxy_NLU_postprocess.py Taxi $1
python3 endtoend/Galaxy_NLU_postprocess.py Hotel $1
python3 endtoend/Galaxy_NLU_postprocess.py Train $1
python3 endtoend/Galaxy_NLU_postprocess.py Attraction+Restaurant $1
python3 endtoend/Galaxy_NLU_postprocess.py Attraction+Hotel $1
python3 endtoend/Galaxy_NLU_postprocess.py Attraction+Train $1
python3 endtoend/Galaxy_NLU_postprocess.py Attraction+Restaurant+Taxi $1
python3 endtoend/Galaxy_NLU_postprocess.py Attraction+Taxi+Hotel $1
python3 endtoend/Galaxy_NLU_postprocess.py Restaurant+Hotel $1
python3 endtoend/Galaxy_NLU_postprocess.py Restaurant+Taxi+Hotel $1
python3 endtoend/Galaxy_NLU_postprocess.py Restaurant+Train $1
python3 endtoend/Galaxy_NLU_postprocess.py Hotel+Train $1
python3 endtoend/Galaxy_NLU_to_pred.py Attraction $1
python3 endtoend/Galaxy_NLU_to_pred.py Restaurant $1
python3 endtoend/Galaxy_NLU_to_pred.py Taxi $1
python3 endtoend/Galaxy_NLU_to_pred.py Hotel $1
python3 endtoend/Galaxy_NLU_to_pred.py Train $1
python3 endtoend/Galaxy_NLU_to_pred.py Attraction+Restaurant $1
python3 endtoend/Galaxy_NLU_to_pred.py Attraction+Hotel $1
python3 endtoend/Galaxy_NLU_to_pred.py Attraction+Train $1
python3 endtoend/Galaxy_NLU_to_pred.py Attraction+Restaurant+Taxi $1
python3 endtoend/Galaxy_NLU_to_pred.py Attraction+Taxi+Hotel $1
python3 endtoend/Galaxy_NLU_to_pred.py Restaurant+Hotel $1
python3 endtoend/Galaxy_NLU_to_pred.py Restaurant+Taxi+Hotel $1
python3 endtoend/Galaxy_NLU_to_pred.py Restaurant+Train $1
python3 endtoend/Galaxy_NLU_to_pred.py Hotel+Train $1